"""empty message

Revision ID: 31307430be8b
Revises: e94d0eafa309
Create Date: 2020-07-08 21:08:42.330821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31307430be8b'
down_revision = 'e94d0eafa309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('updated', sa.DateTime(), nullable=False))
    op.drop_index('ix_article_title', table_name='article')
    op.drop_column('article', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title', mysql.VARCHAR(length=32), nullable=False))
    op.create_index('ix_article_title', 'article', ['title'], unique=False)
    op.drop_column('article', 'updated')
    # ### end Alembic commands ###
