"""empty message

Revision ID: e94d0eafa309
Revises: 05f49289a5e9
Create Date: 2020-07-08 20:14:16.548747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e94d0eafa309'
down_revision = '05f49289a5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=20), nullable=False))
    op.drop_column('user', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('user', 'location')
    op.drop_column('user', 'created')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
